version: '3.8'

services:
  # PostgreSQL 설정
  db:
    image: postgres:15-alpine
    container_name: factory-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Abcd1234
      POSTGRES_DB: factory_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  # MinIO 설정
  minio:
    image: minio/minio
    container_name: factory-minio
    restart: always
    ports:
      - "9000:9000" # API
      - "9001:9001" # WEB
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Abcd1234
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"